### ISSUE TITLE
add fab-production files

### ISSUE THREAD

**Issue by Madouc** [skeatz/FabFTDI#1]
Cool! thanks for these.
to increase adaptation i would add board, outline and component png´s that are ready for production to the repository.

**Comment by skeatz** [comment]
Yup; will do so later. I've been working on these for the past couple of weeks, when I could spare the time. Only just started writing up the tutorials. Will improve upon it as I go along.

**Comment by skeatz** [comment]
Hi Bas,


Noted. Will update documents to include these later. Was working on these boards during the past 2 weeks, when I had the time. Decided to do a quick write-up & post to GitHub late last night, so kind of a rush job.


cheers,

Steven



________________________________

**Comment by skeatz** [comment]
Added traces & outline pngs for fab modules. Board layout & finished board already included.
